export const LocationCategoryEnum = {
	Airport: 'airport',
	AmusementPark: 'amusement-park',
	AncestralHall: 'ancestral-hall',
	Base: 'base',
	Beach: 'beach',
	Bridge: 'bridge',
	Buddhist: 'buddhist',
	Building: 'building',
	Cafe: 'cafe',
	Cave: 'cave',
	Cemetery: 'cemetery',
	Christian: 'christian',
	Civic: 'civic',
	Commercial: 'commercial',
	Community: 'community',
	Dam: 'dam',
	Factory: 'factory',
	Forest: 'forest',
	Forestry: 'forestry',
	Fortification: 'fortification',
	Government: 'government',
	Granary: 'granary',
	Health: 'health',
	Historic: 'historic',
	Hotel: 'hotel',
	HotSpring: 'hot-spring',
	Indigenous: 'indigenous',
	Industrial: 'industrial',
	Infrastructure: 'infrastructure',
	Jewish: 'jewish',
	Kiln: 'kiln',
	Library: 'library',
	Lighthouse: 'lighthouse',
	Market: 'market',
	Military: 'military',
	Mining: 'mining',
	Monument: 'monument',
	Museum: 'museum',
	Muslim: 'muslim',
	Natural: 'natural',
	NightMarket: 'night-market',
	Other: 'other',
	Park: 'park',
	Police: 'police',
	Power: 'power',
	Prison: 'prison',
	PublicArt: 'public-art',
	Railway: 'railway',
	Religious: 'religious',
	Residence: 'residence',
	Restaurant: 'restaurant',
	Road: 'road',
	Salt: 'salt',
	School: 'school',
	Seaport: 'seaport',
	Shinto: 'shinto',
	Shophouse: 'shophouse',
	Site: 'site',
	Temple: 'temple',
	Theater: 'theater',
	Tobacco: 'tobacco',
	Transportation: 'transportation',
	Tree: 'tree',
	Tunnel: 'tunnel',
	Unknown: 'unknown',
	Viewpoint: 'viewpoint',
	Warehouse: 'warehouse',
	Water: 'water', // Should relate to water supply technology
	Waterfall: 'waterfall',
} as const satisfies Record<string, string>;

export const LocationStatusEnum = {
	Abandoned: 'abandoned',
	Active: 'active',
	Converted: 'converted',
	Idle: 'idle',
	Private: 'private',
	Public: 'public',
	Remnants: 'remnants',
	Unknown: 'unknown',
	Vanished: 'vanished',
} as const satisfies Record<string, string>;

export type LocationStatus = (typeof LocationStatusEnum)[keyof typeof LocationStatusEnum];
