packages:
  - packages/**
  - deploy/image-server

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - astro
  - '@astrojs/markdown-remark'
  - '@astrojs/mdx'
  - '@astrojs/node'
  - '@astrojs/react'
  - '@astrojs/rss'
  - '@astrojs/sitemap'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - sharp
  - sqlite3

overrides:
  vite: 6.3.4
