packages:
  - packages/**
  - deploy/site/image-server

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - astro
  - '@astrojs/markdown-remark'
  - '@astrojs/mdx'
  - '@astrojs/node'
  - '@astrojs/react'
  - '@astrojs/rss'
  - '@astrojs/sitemap'
  - '@xsynaptic/eslint-config'
  - '@xsynaptic/unified-tools'
  - 'rehype-wrap-cjk'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - protobufjs
  - sharp
  - sqlite3
