services:
  image-cache:
    image: nginx:1.30.2-alpine
    container_name: dev-image-cache
    ports:
      - '3100:80'
    volumes:
      - ${IMAGE_SERVER_NGINX_CONFIG}:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      image-server:
        condition: service_started

  image-server:
    image: ghcr.io/cshum/imagor-mozjpeg:1.9.1
    container_name: dev-image-server
    volumes:
      - ${CONTENT_MEDIA_PATH}:/media:ro
    environment:
      - IMAGOR_SECRET=${IMAGE_SERVER_SECRET:-dev-secret-do-not-use-in-production}
      - IMAGOR_SIGNER_TYPE=sha256
      - IMAGOR_SIGNER_TRUNCATE=${IMAGE_SERVER_SIGNATURE_LENGTH:-20}
      - VIPS_STRIP_METADATA=1
      - VIPS_MOZJPEG=1
      - FILE_LOADER_BASE_DIR=/media
      - HTTP_LOADER_DISABLE=1
      - IMAGOR_CACHE_HEADER_TTL=8760h
      - IMAGOR_DISABLE_PARAMS_ENDPOINT=1
      - VIPS_MAX_RESOLUTION=16800000
      - VIPS_MAX_WIDTH=5000
      - VIPS_MAX_HEIGHT=5000
