import { GeometryTypeEnum } from '@spectralcodex/shared/map';

export const MapDataKeys = {
	Id: 'id',
	Category: 'category',
	Status: 'status',
	Precision: 'precision',
	Quality: 'quality',
	Rating: 'rating',
	Objective: 'objective',
	Outlier: 'outlier',
	Geometry: 'geometry',
	GeometryType: 'type',
	GeometryCoordinates: 'coordinates',
	Title: 'title',
	TitleMultilingualLang: 'titleMultilingualLang',
	TitleMultilingualValue: 'titleMultilingualValue',
	Url: 'url',
	Description: 'description',
	Safety: 'safety',
	GoogleMapsUrl: 'googleMapsUrl',
	WikipediaUrl: 'wikipediaUrl',
	Image: 'image',
	ImageSrcSet: 'srcSet',
	HasImage: 'hasImage',
	RegionOrdinals: 'regionOrdinals',
	ThemeIndices: 'themeIndices',
	ChunkKey: 'chunkKey',
} as const;

export const MapDataKeysCompressed = {
	Id: 'i',
	Category: 'c',
	Status: 's',
	Precision: 'p',
	Quality: 'q',
	Rating: 'r',
	Objective: 'o',
	Outlier: 'l',
	Geometry: 'g',
	GeometryType: 'j',
	GeometryCoordinates: 'x',
	Title: 't',
	TitleMultilingualLang: 'a',
	TitleMultilingualValue: 'v',
	Url: 'u',
	Description: 'd',
	Safety: 'f',
	GoogleMapsUrl: 'm',
	WikipediaUrl: 'w',
	Image: 'e',
	ImageSrcSet: 'y',
	HasImage: 'n',
	RegionOrdinals: 'b',
	ThemeIndices: 'h',
	ChunkKey: 'k',
} as const satisfies Record<keyof typeof MapDataKeys, string>;

export const MapDataGeometryTypeNumericMapping = {
	[GeometryTypeEnum.Point]: 0,
	[GeometryTypeEnum.MultiPoint]: 1,
	[GeometryTypeEnum.LineString]: 2,
	[GeometryTypeEnum.Polygon]: 3,
	[GeometryTypeEnum.MultiPolygon]: 4,
} as const;
