import type { LocationCategory } from '@spectralcodex/react-map-component';

export const mapMarkerIcons = {
	/** Civic */
	civic: 'material-symbols:question-mark-rounded',
	cemetery: 'material-symbols:question-mark-rounded',
	government: 'mingcute:government-line',
	health: 'mdi:hospital',
	library: 'mingcute:book-6-line',
	museum: 'mdi:museum',
	park: 'map:park',
	police: 'mdi:police-badge-outline',
	prison: 'material-symbols:question-mark-rounded',
	'public-art': 'material-symbols:question-mark-rounded',
	school: 'material-symbols-light:school',
	viewpoint: 'mdi:binoculars',
	water: 'mdi:water',
	/** Commercial */
	attraction: 'material-symbols:star-rate-rounded',
	cafe: 'material-symbols:local-cafe',
	commercial: 'material-symbols:question-mark-rounded',
	hotel: 'material-symbols:question-mark-rounded',
	market: 'mdi:marketplace',
	'night-market': 'material-symbols:question-mark-rounded',
	restaurant: 'mingcute:fork-knife-fill',
	shophouse: 'material-symbols:question-mark-rounded',
	theater: 'material-symbols-light:theaters-rounded',
	'theme-park': 'mingcute:ferris-wheel-fill',
	/** Historic */
	historic: 'mingcute:pavilion-fill',
	memorial: 'material-symbols:question-mark-rounded',
	monument: 'mingcute:palace-line',
	site: 'material-symbols:question-mark-rounded',
	statue: 'material-symbols:question-mark-rounded',
	tomb: 'material-symbols:question-mark-rounded',
	/** Industrial */
	industrial: 'mingcute:factory-2-fill',
	factory: 'mdi:gear',
	forestry: 'mingcute:tree-fill',
	kiln: 'mingcute:factory-2-fill',
	granary: 'material-symbols:question-mark-rounded',
	mining: 'mingcute:diamond-2-line',
	power: 'mdi:electricity',
	salt: 'mdi:warehouse',
	tobacco: 'mdi:warehouse',
	warehouse: 'mdi:warehouse',
	/** Infrastructure */
	infrastructure: 'material-symbols:question-mark-rounded',
	dam: 'mdi:electricity',
	lighthouse: 'mingcute:lighthouse-fill',
	reservoir: 'material-symbols:question-mark-rounded',
	/** Military */
	military: 'material-symbols:military-tech-outline-rounded',
	base: 'material-symbols:military-tech-outline-rounded',
	bunker: 'material-symbols:question-mark-rounded',
	fortification: 'material-symbols:question-mark-rounded',
	/** Natural */
	natural: 'mingcute:tree-fill',
	beach: 'mingcute:umbrella-2-line',
	cave: 'material-symbols:question-mark-rounded',
	forest: 'mingcute:tree-fill',
	'hot-spring': 'material-symbols:question-mark-rounded',
	lake: 'material-symbols:question-mark-rounded',
	rock: 'material-symbols:question-mark-rounded',
	tree: 'material-symbols:question-mark-rounded',
	waterfall: 'material-symbols:question-mark-rounded',
	/** Religious */
	religious: 'mdi:temple-outline',
	'ancestral-hall': 'mdi:temple-outline',
	buddhist: 'mdi:temple-outline',
	christian: 'mdi:christianity',
	indigenous: 'mdi:temple-outline',
	jewish: 'mdi:temple-outline',
	muslim: 'mdi:religion-muslim',
	shinto: 'mingcute:miyajima-torii-fill',
	temple: 'mdi:temple-outline',
	/** Transportation */
	transportation: 'mingcute:bus-2-line',
	airport: 'material-symbols:question-mark-rounded',
	bridge: 'mingcute:bridge-line',
	railway: 'mdi:directions-railway',
	road: 'mingcute:road-line',
	seaport: 'mingcute:anchor-fill',
	tunnel: 'mingcute:tunnel-line',
	/** Various */
	building: 'mingcute:building-2-line',
	community: 'material-symbols:question-mark-rounded',
	residence: 'material-symbols-light:house-rounded',
	other: 'material-symbols:question-mark-rounded',
	unknown: 'mingcute:ghost-line',
} as const satisfies Record<LocationCategory, string>;
