### WordPress to Astro URL redirects ###

# Regions
redir /regions/new-taipei/ /regions/xinbei/ 301
redir /regions/keelung-city/ /regions/keelung/ 301
redir /regions/shln/ /regions/shulin/ 301
redir /regions/dongshi-taichung/ /regions/dongshi/ 301

# Themes
redir /collections/hakka-people/ /themes/taiwan-hakka-culture/ 301
redir /collections/sanheyuan/ /themes/taiwan-sanheyuan/ 301
redir /collections/taiwan-world-war-2-history/ /themes/taiwan-world-war-2/ 301
redir /collections/mosquito-halls/ /themes/taiwan-mosquito-halls/ 301
redir /collections/symbiotic-temples/ /themes/parasitic-temples/ 301
redir /collections/postmodern-architecture/ /themes/taiwan-postmodern-architecture/ 301
redir /collections/japanese-colonial-era/ /themes/taiwan-japanese-colonial-era/ 301
redir /collections/qing-dynasty-era/ /themes/taiwan-qing-dynasty-era/ 301
redir /collections/strange-idols/ /themes/taiwan-temple-culture/ 301
redir /collections/urban-decay/ /themes/urbex/ 301
redir /themes/kmt-authoritarian-era/ /themes/taiwan-kmt-authoritarian-era/ 301

# Keywords to themes
redir /keywords/ /themes/ 301
redir /keywords/art-deco/ /themes/asian-art-deco/ 301
redir /keywords/baroque-revival/ /themes/baroque-revival-architecture/ 301
redir /keywords/theaters/ /themes/taiwan-theaters/ 301
redir /keywords/haunted/ /themes/taiwan-ghost-island/ 301
redir /keywords/temples/ /themes/taiwan-temple-culture/ 301
redir /keywords/urbex/ /themes/urbex/ 301
redir /keywords/earthquakes/ /themes/921-earthquake/ 301
redir /keywords/military/ /themes/taiwan-military-fortifications/ 301
redir /keywords/brick/ /themes/taiwan-brick-industry/ 301
redir /keywords/buddhism/ /themes/taiwan-temple-culture/ 301
redir /keywords/forests/ /themes/taiwan-forestry/ 301
redir /keywords/railways/ /themes/taiwan-railways/ 301
redir /keywords/abandoned/ /themes/urbex/ 301
redir /keywords/cycling/ /themes/taiwan-bicycle-touring/ 301
redir /keywords/theme-parks/ /themes/taiwan-amusement-parks/ 301
redir /keywords/attractions/ /themes/taiwan-tourist-attractions/ 301
redir /keywords/hospitals/ /themes/taiwan-health-history/ 301
redir /keywords/transportation/ /themes/taiwan-transportation-industry/ 301
redir /keywords/schools/ /themes/taiwan-education-history/ 301
redir /keywords/urbanism/ /themes/urbanism/ 301
redir /keywords/fortifications/ /themes/taiwan-military-fortifications/ 301
redir /keywords/highlights/ / 301
redir /keywords/geosophy/ /locations/ 301
redir /keywords/ephemera/ /notes/ 301
redir /keywords/cemeteries/ /themes/ghost-island/ 301
redir /keywords/airports/ /themes/taiwan-transportation-industry/ 301
redir /keywords/road-trips/ /series/ 301
redir /keywords/blogging/ /notes/ 301
redir /keywords/sightings/ /notes/ 301

# Other
redir /section/travelogues/ /posts/ 301

# Wildcard: /collections/* -> /themes/*
@collections path_regexp collections ^/collections/(.*)$
redir @collections /themes/{re.collections.1} 301

### Post-migration redirects ###

# 2026; if we change content type we need to manually specify redirects here
redir /themes/taiwan-mystery/ /resources/taiwan-mystery/ 301
redir /themes/taiwan-parasitic-temples/ /resources/parasitic-temples/ 301

# Opengraph images
@og path_regexp og ^/0g/(.*)$
redir @og /og/{re.og.1} 301

# Timeline to Archives
@timeline path_regexp timeline ^/timeline/(.*)$
redir @timeline /archives/{re.timeline.1} 301
redir /timeline/ /archives/ 301

# Ephemera to Notes
@ephemera path_regexp ephemera ^/ephemera/(.*)$
redir @ephemera /notes/{re.ephemera.1} 301
redir /ephemera/ /notes/ 301
