import type { LocationCategory } from './map-locations';

import { LocationCategoryEnum } from './map-locations';

export const mapMarkerIcons = {
	/** Civic */
	[LocationCategoryEnum.Civic]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Cemetery]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Government]: 'mingcute:government-line',
	[LocationCategoryEnum.Health]: 'mdi:hospital',
	[LocationCategoryEnum.Library]: 'mingcute:book-6-line',
	[LocationCategoryEnum.Museum]: 'mdi:museum',
	[LocationCategoryEnum.Park]: 'map:park',
	[LocationCategoryEnum.Police]: 'mdi:police-badge-outline',
	[LocationCategoryEnum.Prison]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.PublicArt]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.School]: 'material-symbols-light:school',
	[LocationCategoryEnum.Viewpoint]: 'mdi:binoculars',
	[LocationCategoryEnum.Water]: 'mdi:water',
	/** Commercial */
	[LocationCategoryEnum.Attraction]: 'material-symbols:star-rate-rounded',
	[LocationCategoryEnum.Cafe]: 'material-symbols:local-cafe',
	[LocationCategoryEnum.Commercial]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Hotel]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Market]: 'mdi:marketplace',
	[LocationCategoryEnum.NightMarket]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Restaurant]: 'mingcute:fork-knife-fill',
	[LocationCategoryEnum.Shophouse]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Theater]: 'material-symbols-light:theaters-rounded',
	[LocationCategoryEnum.ThemePark]: 'mingcute:ferris-wheel-fill',
	/** Historic */
	[LocationCategoryEnum.Historic]: 'mingcute:pavilion-fill',
	[LocationCategoryEnum.Memorial]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Monument]: 'mingcute:palace-line',
	[LocationCategoryEnum.Site]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Statue]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Tomb]: 'material-symbols:question-mark-rounded',
	/** Industrial */
	[LocationCategoryEnum.Industrial]: 'mingcute:factory-2-fill',
	[LocationCategoryEnum.Factory]: 'mdi:gear',
	[LocationCategoryEnum.Forestry]: 'mingcute:tree-fill',
	[LocationCategoryEnum.Kiln]: 'mingcute:factory-2-fill',
	[LocationCategoryEnum.Granary]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Mining]: 'mingcute:diamond-2-line',
	[LocationCategoryEnum.Power]: 'mdi:electricity',
	[LocationCategoryEnum.Salt]: 'mdi:warehouse',
	[LocationCategoryEnum.Tobacco]: 'mdi:warehouse',
	[LocationCategoryEnum.Warehouse]: 'mdi:warehouse',
	/** Infrastructure */
	[LocationCategoryEnum.Infrastructure]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Dam]: 'mdi:electricity',
	[LocationCategoryEnum.Lighthouse]: 'mingcute:lighthouse-fill',
	[LocationCategoryEnum.Reservoir]: 'material-symbols:question-mark-rounded',
	/** Military */
	[LocationCategoryEnum.Military]: 'material-symbols:military-tech-outline-rounded',
	[LocationCategoryEnum.Base]: 'material-symbols:military-tech-outline-rounded',
	[LocationCategoryEnum.Bunker]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Fortification]: 'material-symbols:question-mark-rounded',
	/** Natural */
	[LocationCategoryEnum.Natural]: 'mingcute:tree-fill',
	[LocationCategoryEnum.Beach]: 'mingcute:umbrella-2-line',
	[LocationCategoryEnum.Cave]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Forest]: 'mingcute:tree-fill',
	[LocationCategoryEnum.HotSpring]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Lake]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Rock]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Tree]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Waterfall]: 'material-symbols:question-mark-rounded',
	/** Religious */
	[LocationCategoryEnum.Religious]: 'mdi:temple-outline',
	[LocationCategoryEnum.AncestralHall]: 'mdi:temple-outline',
	[LocationCategoryEnum.Buddhist]: 'mdi:temple-outline',
	[LocationCategoryEnum.Christian]: 'mdi:christianity',
	[LocationCategoryEnum.Indigenous]: 'mdi:temple-outline',
	[LocationCategoryEnum.Jewish]: 'mdi:temple-outline',
	[LocationCategoryEnum.Muslim]: 'mdi:religion-muslim',
	[LocationCategoryEnum.Shinto]: 'mingcute:miyajima-torii-fill',
	[LocationCategoryEnum.Temple]: 'mdi:temple-outline',
	/** Transportation */
	[LocationCategoryEnum.Transportation]: 'mingcute:bus-2-line',
	[LocationCategoryEnum.Airport]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Bridge]: 'mingcute:bridge-line',
	[LocationCategoryEnum.Railway]: 'mdi:directions-railway',
	[LocationCategoryEnum.Road]: 'mingcute:road-line',
	[LocationCategoryEnum.Seaport]: 'mingcute:anchor-fill',
	[LocationCategoryEnum.Tunnel]: 'mingcute:tunnel-line',
	/** Various */
	[LocationCategoryEnum.Building]: 'mingcute:building-2-line',
	[LocationCategoryEnum.Community]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Residence]: 'material-symbols-light:house-rounded',
	[LocationCategoryEnum.Other]: 'material-symbols:question-mark-rounded',
	[LocationCategoryEnum.Unknown]: 'mingcute:ghost-line',
} as const satisfies Record<LocationCategory, string>;
