import { GeometryTypeEnum } from 'packages/map-types/src/map-geometry';

export const MapDataKeys = {
	Id: 'id',
	Category: 'category',
	Status: 'status',
	Precision: 'precision',
	Quality: 'quality',
	Rating: 'rating',
	Objective: 'objective',
	Outlier: 'outlier',
	Geometry: 'geometry',
	GeometryType: 'type',
	GeometryCoordinates: 'coordinates',
	Title: 'title',
	TitleMultilingualLang: 'titleMultilingualLang',
	TitleMultilingualValue: 'titleMultilingualValue',
	Url: 'url',
	Description: 'description',
	Safety: 'safety',
	GoogleMapsUrl: 'googleMapsUrl',
	WikipediaUrl: 'wikipediaUrl',
	Image: 'image',
	ImageSrc: 'src',
	ImageSrcSet: 'srcSet',
	ImageHeight: 'height',
	ImageWidth: 'width',
} as const;

export const MapDataKeysCompressed = {
	Id: 'i',
	Category: 'c',
	Status: 's',
	Precision: 'p',
	Quality: 'q',
	Rating: 'r',
	Objective: 'o',
	Outlier: 'l',
	Geometry: 'g',
	GeometryType: 'j',
	GeometryCoordinates: 'x',
	Title: 't',
	TitleMultilingualLang: 'a',
	TitleMultilingualValue: 'v',
	Url: 'u',
	Description: 'd',
	Safety: 'f',
	GoogleMapsUrl: 'm',
	WikipediaUrl: 'w',
	Image: 'e',
	ImageSrc: 'b',
	ImageSrcSet: 'y',
	ImageHeight: 'h',
	ImageWidth: 'z',
} as const satisfies Record<keyof typeof MapDataKeys, string>;

export const MapDataKeyMap = {
	[MapDataKeys.Id]: MapDataKeysCompressed.Id,
	[MapDataKeys.Category]: MapDataKeysCompressed.Category,
	[MapDataKeys.Status]: MapDataKeysCompressed.Status,
	[MapDataKeys.Precision]: MapDataKeysCompressed.Precision,
	[MapDataKeys.Quality]: MapDataKeysCompressed.Quality,
	[MapDataKeys.Rating]: MapDataKeysCompressed.Rating,
	[MapDataKeys.Objective]: MapDataKeysCompressed.Objective,
	[MapDataKeys.Outlier]: MapDataKeysCompressed.Outlier,
	[MapDataKeys.Geometry]: MapDataKeysCompressed.Geometry,
	[MapDataKeys.GeometryType]: MapDataKeysCompressed.GeometryType,
	[MapDataKeys.GeometryCoordinates]: MapDataKeysCompressed.GeometryCoordinates,
	[MapDataKeys.Title]: MapDataKeysCompressed.Title,
	[MapDataKeys.TitleMultilingualLang]: MapDataKeysCompressed.TitleMultilingualLang,
	[MapDataKeys.TitleMultilingualValue]: MapDataKeysCompressed.TitleMultilingualValue,
	[MapDataKeys.Url]: MapDataKeysCompressed.Url,
	[MapDataKeys.Description]: MapDataKeysCompressed.Description,
	[MapDataKeys.Safety]: MapDataKeysCompressed.Safety,
	[MapDataKeys.GoogleMapsUrl]: MapDataKeysCompressed.GoogleMapsUrl,
	[MapDataKeys.WikipediaUrl]: MapDataKeysCompressed.WikipediaUrl,
	[MapDataKeys.Image]: MapDataKeysCompressed.Image,
	[MapDataKeys.ImageSrc]: MapDataKeysCompressed.ImageSrc,
	[MapDataKeys.ImageSrcSet]: MapDataKeysCompressed.ImageSrcSet,
	[MapDataKeys.ImageHeight]: MapDataKeysCompressed.ImageHeight,
	[MapDataKeys.ImageWidth]: MapDataKeysCompressed.ImageWidth,
} as const satisfies Record<
	(typeof MapDataKeys)[keyof typeof MapDataKeys],
	(typeof MapDataKeysCompressed)[keyof typeof MapDataKeysCompressed]
>;

export const MapDataGeometryTypeNumericMapping = {
	[GeometryTypeEnum.Point]: 0,
	[GeometryTypeEnum.MultiPoint]: 1,
	[GeometryTypeEnum.LineString]: 2,
} as const;
